id = "codegreen"
name = "code_green"
version = "0.0.1"
schema_version = 1
authors = ["ningfangbin"]
description = "The theme is mainly in green color."
repository = "https://github.com/ningfangbin/zed_code_green.git"