id = "green-theme"
name = "green-theme"
version = "0.0.2"
schema_version = 1
authors = ["ningfangbin <nfb0408@163.com>"]
description = "The theme is mainly in green color."
repository = "https://github.com/ningfangbin/zed_code_green.git"